# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sxqUevrPwZCqc0XOzfRrUjvSj--fS9Vg
"""

import math

def euclidean_distance(x1, y1, x2, y2):
    return math.sqrt((x2 - x1)**2 + (y2 - y1)**2)
x1, y1 = 1, 2
x2, y2 = 4, 6
distance = euclidean_distance(x1, y1, x2, y2)
print(f"Öklid mesafesi: {distance}")